version: "3"

services:
    psiturk:
        build: .
        volumes:
            - ./data:/data
        ports:
            - "12391:22362"
        command: bash -c "psiturk server on && tail -F /dev/null"
