---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(lme4)
library(lmerTest)
```

```{r}
df <- read_csv(
  "merged_df.csv",
  col_types = list(
    uniqueid = col_factor()
  ))
glimpse(df)
```
```{r}
filtered_df <- df %>% filter(!slider_copout, !(condition_0 %in% c("practice", "filler"))) %>% 
  mutate(agent_is_concrete=`A concrete?`,
         location_is_subject=!agent_is_subject)
contrasts(filtered_df$location_is_subject) = c(-1, 1)
contrasts(filtered_df$agent_is_concrete) = c(-1, 1)
```


```{r}
model <- lmer(slider_value ~ location_is_subject * agent_is_concrete + (1|item_id) + (agent_is_subject * agent_is_concrete|uniqueid),
              data=filtered_df)
summary(model)
```
```{r}
ranef(model)
```
```{r}
library(brms)
```


```{r}
filtered_df_trans <- filtered_df %>% 
  mutate(slider_value = (slider_value + 0.1) / 100.2)
model.exp00.brm <- brm(slider_value ~ location_is_subject * agent_is_concrete
                                      + (location_is_subject|item_id)
                                      + (location_is_subject * agent_is_concrete|uniqueid),
                       data=filtered_df_trans, family="beta")
```
```{r}
summary(model.exp00.brm)
```

## Visualization

```{r}
interactions::cat_plot(model.exp00.brm, y.label="Slider response value (0–1)",
                       pred=location_is_subject, pred.values=c(TRUE, FALSE), pred.labels=c("L (The garden is swarming)", "A (Bees are swarming)"), x.label="Construction",
                       modx=agent_is_concrete, modx.values=c(FALSE, TRUE), modx.labels=c("Abstract agent", "Concrete agent"), legend.main="Concreteness")
                       #modx=agent_is_given, modx.values=c(TRUE, FALSE), modx.labels=c("Bees", "The garden"), legend.main="Given",
                       #mod2=agent_is_concrete, mod2.values=c(FALSE, TRUE), mod2.labels=c("Abstract agent", "Concrete agent"))

ggsave("catplot_slider_construction-concreteness.png")
```

